### ISSUE TITLE
ODK Survey 'select_one_dropdown' item appears selected but is not

### ISSUE THREAD

**Issue by LipServiceLibrarian** [opendatakit/opendatakit#1234] opened 2016-07-04 01:48 UTC
Styling problem for ODK Survey 'select_one_dropdown' type
-------------

- When using the 'select_one_dropdown' type in an ODK Survey form, the first option in the choices list appears to be selected by default.
- On navigating to the next page of the form, this field fails 'required' validation as it is not selected. 
- If another choice is selected, and then the first choice in the list is selected, the selection is valid.

![screen shot 2016-07-04 at 11 34 42 am](https://cloud.githubusercontent.com/assets/2177110/16548977/c37d5220-41dc-11e6-814d-277dba666057.png)
![screen shot 2016-07-04 at 11 36 02 am](https://cloud.githubusercontent.com/assets/2177110/16548974/c2316e9c-41dc-11e6-80ca-ef4e2c8dce2b.png)

**Comment by bvnbbn** [comment] 2016-07-04 04:09
hey man can you tell  me how did you import collect app from github I am
getting error

**Comment by clarlars** [comment] 2016-07-06 22:14
@bvnbbn This is not the appropriate place for this comment.  Please don't pollute other issues with irrelevant information.

**Comment by wvdm1217** [comment] 2016-07-11 13:43
The default selected value is not passed on when selected. When there are 2 values the default dropdown is also not passed on unless the second value is selected and then the first value is selected 
thereafter.

**Comment by magdalenacassel** [comment] 2016-08-23 05:10
The issue appears to be resolved for select_one_dropdown as of 2.0.126.  Should this be marked as Resolved?

**Comment by acawood777** [comment] 2016-09-02 14:41
I can also confirm that this is now working (on the project reported by wvdm1217 above).

One request though - the current default if nothing is selected is "text_undefined". Can that please be changed to "not specified" as is currently done for empty string/number prompts?

**Comment by acawood777** [comment] 2016-09-06 16:13
Update: 
I support marking this as Resolved.

The issue I was seeing was caused by /opendatakit/default/config/assets/framework/translations.js being overwritten by the older version of the file that was on Aggregate when syncing. The older version did not have the "Choose option" text defined, hence "text_undefined" being displayed.
Ensuring that the newer version was synced to Aggregate solved my issue.

**Comment by clarlars** [comment] 2016-09-06 18:33
Thanks for the comments.  I will close this issue now.

**Closed by clarlars** 2016-09-06 18:33 UTC
Labels: Survey
