### ISSUE TITLE
Survey Failure rendering when row has errors 

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/opendatakit#1407] opened 2018-08-13 22:49 UTC
#### Software and hardware versions 
Survey 2.0.5.

#### Problem description
Survey will hang on initialization if row data is problematic

Example error:
Uncaught RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object._successCbFn (database.js:471)
    at Object.invokeCallbackFn (odkData.js:373)
    at odkData.js:396

#### Steps to reproduce the problem
Setup server with geotagger and this data
[Bug.zip](https://github.com/opendatakit/opendatakit/files/2284971/Bug.zip)

**Comment by clarlars** [comment] 2018-08-28 02:17
Could not reproduce this issue on Survey 2.0.5.  This should have been fixed by https://github.com/opendatakit/sync-endpoint/pull/7.

**Closed by clarlars** 2018-08-28 02:17 UTC
Labels: Survey
